// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoufirTours.Models;

#nullable disable

namespace NoufirTours.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260307012730_initialCreate2")]
    partial class initialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NoufirTours.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings");
                });

            modelBuilder.Entity("NoufirTours.Data.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("action");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_user");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("NoufirTours.Data.AutoTripPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ActivationModeInt")
                        .HasColumnType("int")
                        .HasColumnName("activation_mode");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<int>("IsEnabledInt")
                        .HasColumnType("int")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("ScheduleTypeInt")
                        .HasColumnType("int")
                        .HasColumnName("schedule_type");

                    b.Property<string>("SpecificDate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("specific_date");

                    b.Property<long?>("UpdatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<bool>("isDone")
                        .HasColumnType("bit")
                        .HasColumnName("is_done");

                    b.HasKey("Id");

                    b.ToTable("AutoTripPlans", (string)null);
                });

            modelBuilder.Entity("NoufirTours.Data.AutoTripPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("BusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bus_id");

                    b.Property<string>("DepartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("depart_time");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<string>("DropoffPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dropoff_place");

                    b.Property<string>("FromCity")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("from_city");

                    b.Property<int>("IsEnabledInt")
                        .HasColumnType("int")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int")
                        .HasColumnName("order_no");

                    b.Property<decimal>("PickupLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("pickup_lat");

                    b.Property<decimal>("PickupLon")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("pickup_lon");

                    b.Property<string>("PickupPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("pickup_place");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("plan_id");

                    b.Property<int>("PriceTypeInt")
                        .HasColumnType("int")
                        .HasColumnName("price_type");

                    b.Property<decimal>("SeatPriceGo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("seat_price_go");

                    b.Property<decimal>("SeatPriceReturn")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("seat_price_return");

                    b.Property<string>("ToCity")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("to_city");

                    b.Property<string>("TripName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("trip_name");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverId");

                    b.HasIndex("PlanId", "OrderNo")
                        .IsUnique();

                    b.ToTable("AutoTripPlanItems", (string)null);
                });

            modelBuilder.Entity("NoufirTours.Data.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("BookingTypeInt")
                        .HasColumnType("int")
                        .HasColumnName("booking_type");

                    b.Property<string>("CancelNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cancel_note");

                    b.Property<long?>("CanceledAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("canceled_at");

                    b.Property<Guid?>("CanceledByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("canceled_by_user_id");

                    b.Property<string>("CompanyFrom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("company_from");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("customer_name");

                    b.Property<Guid?>("DestinationPlaceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("destination_place_id");

                    b.Property<string>("DestinationPlaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("destination_place_name");

                    b.Property<int>("IsCanceledInt")
                        .HasColumnType("int")
                        .HasColumnName("is_canceled");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("notes");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ReturnDateTime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("return_datetime");

                    b.Property<Guid?>("ReturnDestinationPlaceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("return_destination_place_id");

                    b.Property<string>("ReturnDestinationPlaceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("return_destination_place_name");

                    b.Property<Guid?>("ReturnTripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("return_trip_id");

                    b.Property<string>("SeatsReturnText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seats_return");

                    b.Property<string>("SeatsText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seats");

                    b.Property<int>("StatusInt")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("CanceledByUserId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_bookings_created_by_user");

                    b.HasIndex("DestinationPlaceId");

                    b.HasIndex("ReturnDestinationPlaceId");

                    b.HasIndex("ReturnTripId")
                        .HasDatabaseName("idx_bookings_return_trip");

                    b.HasIndex("TripId")
                        .HasDatabaseName("idx_bookings_trip");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("NoufirTours.Data.BookingCode", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("code");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.HasKey("BookingId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("booking_codes");
                });

            modelBuilder.Entity("NoufirTours.Data.BookingCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<long>("CollectedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("collected_at");

                    b.Property<Guid>("CollectedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("collected_by_user_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("method");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("idx_booking_collections_booking");

                    b.HasIndex("CollectedByUserId")
                        .HasDatabaseName("idx_booking_collections_user");

                    b.ToTable("booking_collections");
                });

            modelBuilder.Entity("NoufirTours.Data.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<long?>("ArchivedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("archived_at");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("archived_by_user_id");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("bus_number");

                    b.Property<string>("BusType")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("bus_type");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("chassis_number");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("color");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<int>("IsActiveInt")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<int>("IsArchivedInt")
                        .HasColumnType("int")
                        .HasColumnName("is_archived");

                    b.Property<int>("LayoutHeight")
                        .HasColumnType("int")
                        .HasColumnName("layout_height");

                    b.Property<int>("LayoutWidth")
                        .HasColumnType("int")
                        .HasColumnName("layout_width");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("ModelName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("model_name");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int")
                        .HasColumnName("model_year");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("plate_number");

                    b.Property<int?>("SeatsCount")
                        .HasColumnType("int")
                        .HasColumnName("seats_count");

                    b.Property<string>("Specs")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("specs");

                    b.HasKey("Id");

                    b.HasIndex("BusNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_buses_bus_number");

                    b.HasIndex("ChassisNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_buses_chassis_number");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_buses_plate_number")
                        .HasFilter("[plate_number] IS NOT NULL");

                    b.ToTable("buses");
                });

            modelBuilder.Entity("NoufirTours.Data.BusSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_driver_id");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bus_id");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<double?>("DoorOffset")
                        .HasColumnType("float")
                        .HasColumnName("door_offset");

                    b.Property<string>("DoorSide")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("door_side");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("element_type");

                    b.Property<int>("IsActiveInt")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("label");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("SeatCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("seat_code");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("pos_x");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("pos_y");

                    b.HasKey("Id");

                    b.HasIndex("BusId", "SeatCode")
                        .IsUnique()
                        .HasDatabaseName("ux_bus_seats_busid_seatcode")
                        .HasFilter("[seat_code] IS NOT NULL");

                    b.ToTable("bus_seats");
                });

            modelBuilder.Entity("NoufirTours.Data.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at_unix");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("FullName", "Phone")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_name_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("NoufirTours.Data.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address");

                    b.Property<long?>("ArchivedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("archived_by_user_id");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("full_name");

                    b.Property<int>("IsActiveInt")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<int>("IsArchivedInt")
                        .HasColumnType("int")
                        .HasColumnName("is_archived");

                    b.Property<long>("JoinedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("joined_at");

                    b.Property<long?>("LicenseExpiryAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("license_expiry_at");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("license_number");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("national_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("ux_drivers_national_id");

                    b.ToTable("drivers");
                });

            modelBuilder.Entity("NoufirTours.Data.DriverPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<int>("IsPrimaryInt")
                        .HasColumnType("int")
                        .HasColumnName("is_primary");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_phones_phone_number");

                    b.HasIndex("DriverId", "PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_phones_driverid_phone");

                    b.ToTable("driver_phones");
                });

            modelBuilder.Entity("NoufirTours.Data.TechnicalSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyPhone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ComplaintsPhone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("bit");

                    b.Property<long>("UpdatedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TechnicalSupports");
                });

            modelBuilder.Entity("NoufirTours.Data.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<long?>("ArchivedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("archived_by_user_id");

                    b.Property<Guid?>("AutoPlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("auto_plan_id");

                    b.Property<Guid?>("AutoPlanItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("auto_plan_item_id");

                    b.Property<Guid?>("BusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bus_id");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("depart_date");

                    b.Property<string>("DepartTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("depart_time");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<string>("DriverName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("driver_name");

                    b.Property<string>("DriverPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("driver_phone");

                    b.Property<Guid?>("DriverUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_user_id");

                    b.Property<decimal?>("DropoffLat")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("dropoff_lat");

                    b.Property<decimal?>("DropoffLon")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("dropoff_lon");

                    b.Property<string>("DropoffPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dropoff_place");

                    b.Property<string>("FromCity")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("from_city");

                    b.Property<int>("IsActiveInt")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<int>("IsArchivedInt")
                        .HasColumnType("int")
                        .HasColumnName("is_archived");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PickupLat")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("pickup_lat");

                    b.Property<decimal?>("PickupLon")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("pickup_lon");

                    b.Property<string>("PickupPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("pickup_place");

                    b.Property<int>("PriceTypeInt")
                        .HasColumnType("int")
                        .HasColumnName("price_type");

                    b.Property<decimal>("SeatPriceGo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("seat_price_go");

                    b.Property<decimal>("SeatPriceReturn")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("seat_price_return");

                    b.Property<string>("ToCity")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("to_city");

                    b.Property<string>("TripName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("trip_name");

                    b.Property<int>("TripOriginInt")
                        .HasColumnType("int")
                        .HasColumnName("trip_origin");

                    b.HasKey("Id");

                    b.HasIndex("BusId")
                        .HasDatabaseName("idx_trips_bus_id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("idx_trips_driver_id");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("IsActiveInt")
                        .HasDatabaseName("idx_trips_active");

                    b.HasIndex("IsArchivedInt")
                        .HasDatabaseName("idx_trips_archived");

                    b.HasIndex("DepartDate", "BusId")
                        .IsUnique()
                        .HasDatabaseName("ux_trips_depdate_busid")
                        .HasFilter("[is_archived] = 0 AND [bus_id] IS NOT NULL");

                    b.HasIndex("DepartDate", "DepartTime")
                        .HasDatabaseName("idx_trips_depart_dt");

                    b.HasIndex("DepartDate", "DriverId")
                        .IsUnique()
                        .HasDatabaseName("ux_trips_depdate_driverid")
                        .HasFilter("[is_archived] = 0 AND [driver_id] IS NOT NULL");

                    b.HasIndex("DepartDate", "TripName")
                        .IsUnique()
                        .HasDatabaseName("ux_trips_depdate_tripname")
                        .HasFilter("[is_archived] = 0");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("NoufirTours.Data.TripPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("IsActiveInt")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<double?>("Lat")
                        .HasColumnType("float")
                        .HasColumnName("lat");

                    b.Property<double?>("Lon")
                        .HasColumnType("float")
                        .HasColumnName("lon");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("place_name");

                    b.Property<int>("PlaceTypeInt")
                        .HasColumnType("int")
                        .HasColumnName("place_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("trip_places");
                });

            modelBuilder.Entity("NoufirTours.Data.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<int>("IsActiveInt")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pass_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("RoleText")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("username");

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("NoufirTours.Data.AuditLog", b =>
                {
                    b.HasOne("NoufirTours.Data.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoufirTours.Data.AutoTripPlanItem", b =>
                {
                    b.HasOne("NoufirTours.Data.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NoufirTours.Data.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NoufirTours.Data.AutoTripPlan", "Plan")
                        .WithMany("Items")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Driver");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("NoufirTours.Data.Booking", b =>
                {
                    b.HasOne("NoufirTours.Data.User", "CanceledByUser")
                        .WithMany("CanceledBookings")
                        .HasForeignKey("CanceledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NoufirTours.Data.User", "CreatedByUser")
                        .WithMany("BookingTrips")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoufirTours.Data.TripPlace", "DestinationPlace")
                        .WithMany()
                        .HasForeignKey("DestinationPlaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NoufirTours.Data.TripPlace", "ReturnDestinationPlace")
                        .WithMany()
                        .HasForeignKey("ReturnDestinationPlaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NoufirTours.Data.Trip", "ReturnTrip")
                        .WithMany()
                        .HasForeignKey("ReturnTripId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NoufirTours.Data.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanceledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DestinationPlace");

                    b.Navigation("ReturnDestinationPlace");

                    b.Navigation("ReturnTrip");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("NoufirTours.Data.BookingCode", b =>
                {
                    b.HasOne("NoufirTours.Data.Booking", "Booking")
                        .WithOne("CodeInfo")
                        .HasForeignKey("NoufirTours.Data.BookingCode", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("NoufirTours.Data.BookingCollection", b =>
                {
                    b.HasOne("NoufirTours.Data.Booking", "Booking")
                        .WithMany("Collections")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoufirTours.Data.User", "CollectedByUser")
                        .WithMany("CollectedPayments")
                        .HasForeignKey("CollectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("CollectedByUser");
                });

            modelBuilder.Entity("NoufirTours.Data.BusSeat", b =>
                {
                    b.HasOne("NoufirTours.Data.Bus", "Bus")
                        .WithMany("Seats")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("NoufirTours.Data.DriverPhone", b =>
                {
                    b.HasOne("NoufirTours.Data.Driver", "Driver")
                        .WithMany("Phones")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("NoufirTours.Data.Trip", b =>
                {
                    b.HasOne("NoufirTours.Data.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NoufirTours.Data.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NoufirTours.Data.User", "DriverUser")
                        .WithMany("DriverTrips")
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bus");

                    b.Navigation("Driver");

                    b.Navigation("DriverUser");
                });

            modelBuilder.Entity("NoufirTours.Data.TripPlace", b =>
                {
                    b.HasOne("NoufirTours.Data.Trip", "Trip")
                        .WithMany("Places")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("NoufirTours.Data.AutoTripPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NoufirTours.Data.Booking", b =>
                {
                    b.Navigation("CodeInfo");

                    b.Navigation("Collections");
                });

            modelBuilder.Entity("NoufirTours.Data.Bus", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("NoufirTours.Data.Driver", b =>
                {
                    b.Navigation("Phones");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("NoufirTours.Data.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("NoufirTours.Data.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BookingTrips");

                    b.Navigation("CanceledBookings");

                    b.Navigation("CollectedPayments");

                    b.Navigation("DriverTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
